### ISSUE TITLE
Keyboard on Acer SW5-012

### ISSUE THREAD

**Issue by SWW13** [AdamWill/baytrail-m#5]
Hi,

you maybe want to add https://github.com/SWW13/hid-synaptics to your kernel modules, it fixes the attachable keyboard on Acer SW5-012 (invalid rdesc). The fix isn't ready for upstream, but it's already working.

Kernel patch file: https://gist.github.com/SWW13/607149459da39493728c#file-0001-hid-add-driver-for-synaptics-keybard-with-broken-rde-patch

**Comment by hadess** [comment]
Hey Simon,

Could you send an email to the fedora-kernel list[1] instead? This would reduce the number of downstream patches in Adam's kernels.

[1]: https://admin.fedoraproject.org/mailman/listinfo/kernel

**Comment by floe** [comment]
Just for reference, this patch is also required for the keyboard dock of the SW5-171.

**Comment by hadess** [comment]
Has the patch been upstreamed since?

**Comment by SWW13** [comment]
looks like i missed some responses to my patch, so it's not upstream yet. but i'll take care of it.

FYI: input mailinglist archive: http://www.spinics.net/lists/linux-input/msg36123.html

**Comment by hadess** [comment]
@SWW13,  @bentiss asked me to ask you for the output of hid-recorder on that device (without your patches obviously). He thinks that we could patch hid-core to clamp to HID_MAX_USAGES when an obviously wrong number of max usages is parsed.

http://bentiss.github.io/hid-replay-docs/

**Comment by bentiss** [comment]
@SWW13 Actually, you might need to have the following applied for hid-recorder to work:
http://www.spinics.net/lists/linux-input/msg36222.html
 I'll figure out what was the original report descriptor by myself then.

**Comment by SWW13** [comment]
@hadess @bentiss Well, that is my patch :)

I'm a bit busy atm so it may take some days till I find time for testing, I'll let you know when I'm done.

FYI The broken / fixed descriptor is here: https://github.com/SWW13/hid-acer/blob/dfdb59376c680e6f9f0af8d2af33dbe9613f40f0/hid-synaptics.cL106
Line 106 and 107 was changed from 0xFF, 0xFF to 0xFF, 0x00 which was detected by the rdesc tool I used to decrypt / comment.

**Comment by bentiss** [comment]
@SSW13 I am about to send http://paste.fedoraproject.org/247902/14377523/ upstream. It should make hid-core accepting your device now. If you could give a try, that would be great.

**Comment by SWW13** [comment]
That should work and looks like a good solution for this type of problems, thanks :)
I don't have my tablet here, so I can't test now. I'll ask some of the people who have contacted my about the keyboard fix.

**Comment by bentiss** [comment]
OK, then I'll send it upstream right away, and we should be able to fix it if this does not work for somebody else.

**Comment by hadess** [comment]
A kernel with the patch applied is available here:
http://copr.fedoraproject.org/coprs/hadess/32bit-boot/build/105505/

And, as the fixes are getting upstream, I'll close this bug. Thanks @bentiss for your help!
